### ISSUE TITLE
Run the tests in GH actions?

### ISSUE THREAD

**Issue by kinow** [rosepearson/GeoFabrics#13]
Since the code is hosted here on GH, and GH actions is free, maybe it could be used to run the tests in the `tests` folder?

Probably a simple workflow, with the `checkout` action to clone the repo, then `setup-python`, then either `pip install` after installing the requirements, or `conda env create -n environment.yml` (might need another step to install conda, or use a Docker container)... then another step that runs the tests.

This way PR's can be validated automatically by GH Actions.

Cheers
Bruno

**Comment by rosepearson** [comment]
Mint. As part of this I think we will have to resolve the apparently missing dependencies that leads `pip install git+https://github.com/rosepearson/GeoFabrics` to fail in a clean conda environment for instance.
