### ISSUE TITLE
Add Dataset ID variable to the output netCDF data for better identify the source data

### ISSUE THREAD

**Issue by xandercai** [rosepearson/GeoFabrics#160]
We can set up LiDAR datasets by the instructions, e.g.:

```
{
  "instructions": {
  ...
    "apis": {
      "lidar": {
        "open_topography": {
          "Rangiora_2014": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          },
          "NZ20_Cant2": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          }
    ...
```

But from the output netCDF file, we do not know a pixel comes from which dataset.

Adding a Data ID variable in the netCDF data denoting the source dataset of each pixel could be helpful for data analysis.

We can add the `dataset_id` field in the instructions below and pass it to the Dataset ID variable in the output netCDF data during the GeoFabrics process.

```
{
  "instructions": {
  ...
    "apis": {
      "lidar": {
        "open_topography": {
          "Rangiora_2014": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          "dataset_id": 2
          },
          "NZ20_Cant2": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
              }
              "dataset_id": 31
            }
    ...
```

**Comment by rosepearson** [comment]
Nice proposal @xandercai! Can you create a PR from the commits on your fork? I'm looking forward to incorporating this into GeoFabrics :)

**Comment by xandercai** [comment]
Thank you, Rose. Sorry for not pulling the request yet. I changed the way to pass dataset id to netCDF from adding a dataset_id field for each dataset to adding a `dataset mapping` dict in the `instructions` dict as below:

```
{
  "instructions": {
  ...
    "apis": {
      "lidar": {
        "open_topography": {
          "Rangiora_2014": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
            }
          },
          "NZ20_Cant2": {
            "crs": {
              "horizontal": 2193,
              "vertical": 7839
              }
            }
    ...
    "dataset_mapping": {
      "Rangiora_2014": 2
      "NZ20_Cant2": 31
     }
...
```

In this way, only one file `dem.py` need to modify, a bit simpler.

So it takes some time to modify and test. I will PR now.

**Comment by rosepearson** [comment]
No worries at all. I'm just working through my own PR and then will trigger the test process for your branch and begin reviewing it. Thanks for the PR :)
