### ISSUE TITLE
Dask improvements

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#208]
This is an issue for an upcoming NeSI consultancy with @jennan. The focus will be on improving the performance and stability of GeoFabrics for larger scale problems.

Focus on better making use of Dask throughout the GeoFabrics stages. Two identified areas are:
* **_RasterArray.interpolate_na_** for 2D interpolation to remove NaN values
* _**RasterArray.clip**_ in series for identifying the lowest value along a waterways

**_RasterArray.interpolate_na_**
Profiling has shown that pinch points are quite different for larger scale problems than smaller problems. Take the two profiles below. 
1. is a 6min problem with all geofabric stages. (small_2m_res.html)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/db4ba016-e7a8-42c1-939c-1c0e94cb2228)

2. is a 4hr problem with all geograbric stages. The only difference with 1 is it is 1m instead of 2m resolution. (small_1m_res.html)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/ff4ca668-2f13-4d4f-94af-7b93e73f0608)

_**RasterArray.clip**_
Another area of focus (although it hasn't showed up as an issue in the 1m profiling it is vivible in the 2m) is 
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/283cbe29-e28c-4c59-9efe-b10d3b1ec1bd)
Could make use of either pandas or dask-geopandas. A weak attempt that I didn't get off the ground can be seen as a comment in processor.py
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/18faf3ee-7137-4d42-aae3-a46c2aa5f654)

Also worth noting that we may be able to do this more directly using a rolling.min call to the xarray with an appropriate size window.

**Comment by rosepearson** [comment]
Have also noticed some unexpected failures with Dask TimeOut/Heartbeat errors. In some instances this is actually after the final chunk appears to have been written to file.

**Comment by rosepearson** [comment]
[job.err.txt](https://github.com/rosepearson/GeoFabrics/files/12888593/job.err.txt)
 Attached Cylc job.err file illustrating the Dask TimeOut/Heartbeat errors.

**Comment by jennan** [comment]
@rosepearson is it making the whole code crash? Dask can be a bit verbose with errors during the tearing down procedure of the Dask cluster... although this doesn't cause any real issue (apart from logs reporting errors) in my experience.

**Comment by rosepearson** [comment]
@jennan it is making the whole Cylc task crash. I have another one below where we hit the time limit - but again the file had been completely written out. It could be a coincident that the file just finished writing before the time limit was reached and it didn't have time to execute the print "Job Succeeded".. but it seems to me like there might be something slightly fishy. Just attaching as a reference for now - not expecting any action on this ticket right now :)

**Comment by rosepearson** [comment]
[job.err.txt](https://github.com/rosepearson/GeoFabrics/files/12889159/job.err.txt)
Attached another Cylc job.err file. Again lots of verbose Task errors. The task ultimately failed after hitting the time limit - it had written out a complete file prior to hitting the time limit, however.

**Comment by rosepearson** [comment]
Noting another repeated error that occurs for a particular roughness run. It repeatedly fails when launched on Maui through Cylc, but has completed producing the expected output. e.e. appears to be a false failure. I have checked running on the NIWA maui nodes without SLURM accessed through https://jupyter.maui.niwa.co.nz/ and it runs fine there. _**This might be a good first place to look into regarding seemingly random errors after the job has run successfully.**_ 
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/81201d07-d398-4725-8e61-7c63adabc458)
[job.err.txt](https://github.com/rosepearson/GeoFabrics/files/12910836/job.err.txt)

tile 2728. roughness stage. takes ~15min.

**Comment by rosepearson** [comment]
One more note about the failures I'm experiencing. They are often related to 

```
/nesi/project/niwa03440/conda/envs/geofabrics/lib/python3.11/site-packages/distributed/client.py:3160: UserWarning: Sending large graph of size 12.85 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
2023-10-14 11:35:39,162 - distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/nesi/project/niwa03440/conda/envs/geofabrics/lib/python3.11/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nesi/project/niwa03440/conda/envs/geofabrics/lib/python3.11/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 272, in msgpack._cmsgpack.Packer._pack
ValueError: memoryview is too large
2023-10-14 11:35:39,163 - distributed.comm.utils - ERROR - memoryview is too large
```

**Comment by rosepearson** [comment]
Looking back through my notes/comments:
* An instance of tile 2728. roughness stage. takes taking ~15min then failing with the file completed.
* An `ValueError: memoryview is too large` error occurs for the waterway stage of tiles 3128, 3130, 3131, 3532
* An `ValueError: 3615135876 exceeds max_bin_len(2147483647)` error occurs in the waterway stage for 3431

I've also been thinking about how I break up the course DEM stage into a bunch of explicit chunks and wonder if that would be best to leave up to Dask. 
* Currently load the same coarse .tif tile many times clipping it to a very small size each time and interpolating points pulled from the XArray
* I could/should? instead load with chunking set to true and use the XArray interp function to upsample with linear interpolation. I then have a raster mask I would use to decide where to replace the DEM with these new values using xarray.where()

**Comment by rosepearson** [comment]
Tile 2627 roughness
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/b56414a6-21f8-4248-8c20-f2119e6d9cc8)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/a5b36c2f-5c3c-4a41-88b2-c59a6baaff21)

**Comment by rosepearson** [comment]
# Update after Consultancy 1
Have made some of the agreed changes:
* Save out LiADR only temp netCDF
* Optionally save the no_data_mask to the netCDF
* Load in the coarse DEM without chunking

I've been looking into xarray.interp with chunking. I've come across the following cases:
1. closed - interpolate a dask-based xarray between chunk of data- https://github.com/pydata/xarray/issues/4078
2. closed - Implement interp for interpolating between chunks of data - https://github.com/pydata/xarray/pull/4155
3. open - dask implementation of np.interp - https://github.com/dask/dask/issues/6474

I've also tried various ways to force/encourage dask in the interp call:
* coarse_dem = coarse_dem.interp(x=dask.array.from_array(self._dem.x, 1000), y=dask.array.from_array(self._dem.y), method="linear")
  *  Error - in _validate_interp_indexers raise TypeError(type(v))
* coarse_dem.chunk(1000).interp(x=dask.array.self._dem.x, y=self._dem.y, method="linear")
  * No error, but result has only one chunk. Get memory errors... but runs for a bit before failure
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/e3866d5e-a8f0-4857-a827-82be5022d8bd)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/439a7e85-985f-448a-b440-16f02e7ccea7)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/781037db-8c42-4076-8ec7-1e35dc0b2d2f)
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/e3d320e3-39e8-4519-a20e-e294aac2d7c3)

* I tried with both the normal chunk size and also one that was 8x smaller given the coarse resolution is 8x bigger.
* It started saving out a file, but did not succeed in completely writing the file. 

### Questions
* Is xarray.interp implemented with dask support - see dashboard screen captures it seems to run across cores
* Should we chunk the coarse_dem after all as chunking the x/y dims on their own don't seem to work...

**Comment by rosepearson** [comment]
@jennan thanks for your notebook. I've implemented it with a few minor tweaks to deal with the std map layout (yx with y decreasing). Also a seemingly odd issue where the chunking needs dask.array.map_blocks needs the second array to have a chunk of its length or smaller - odd at the first array is autmatically given a chunk of its size if the specified chunk size is greater. 
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/6cfe7c40-e93e-461b-a315-6eecccd34998)

Test profiling for tests/test_dem_generation_westport_4/test_dem_generation_westport_4.py
top chunking to 10 - gives 4x5 chunks
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/0866120c-2cca-47ea-b7e1-7c6fa7c3c375)
where the 
bottom xhunking to 300 - gives 1x1 chunks
![image](https://github.com/rosepearson/GeoFabrics/assets/22883860/5a980bc2-0ed5-4e09-9a08-65125e6d29c9)

**Comment by rosepearson** [comment]
# Update from consultancy 2
* Pulled changes from first consultancy into main - See [Issue 219](https://github.com/rosepearson/GeoFabrics/issues/219)
* Running the Cylc suite over ~40 tiles (of 425)
* Record - Success/Failure and run time for successful execution compared to last time.

**Comment by rosepearson** [comment]
# Consultancy 3
## Tasks for Rose
* Collect logs into a folder under niwa03440
* Check if increasing the retry count helps - `export DASK_DISTRIBUTED__COMM__RETRY__COUNT=3`
* Find the `Dask` folder is created - `dask-worker-space`
