### ISSUE TITLE
DEM - Spurious local low elevation and rivers dug too deep

### ISSUE THREAD

**Issue by JoePelmard** [rosepearson/GeoFabrics#218]
In the new DEM generated for the Heretaunga plains (Napier), I found a spurious hole in the Oingo lake with z going to -100m when elevations around this location are about 20m (see image below Location: x=1921706 ; y=5614662)
![image](https://github.com/rosepearson/GeoFabrics/assets/64444193/b204d96a-3bab-4454-96c2-96bcd3eb34d4)

Similarly in the Aropaoanui catchment, the te Ngarue stream is dug too deep ( z going to -40m, see image below). This might appear in other tiles.
![image](https://github.com/rosepearson/GeoFabrics/assets/64444193/a481bbe3-5317-4a7d-88ed-07e77ddd5e26)

After talking with Alice, I was suggested to raise an issue in here.

Regards,
Joe

**Comment by rosepearson** [comment]
Thanks @JoePelmard. This has been addressed through updating the parameters being used to control how the DEM is generated. I will close this here. For your record the case where this was addressed is: https://git.niwa.co.nz/flood-resilience-aotearoa/cylc-combine-geofabric-tiles/-/issues/4
