### ISSUE TITLE
Compress output NetCDF files

### ISSUE THREAD

**Issue by CyprienBosserelle** [rosepearson/GeoFabrics#236]
using a deflation on Netcdf files will reduce file size by hopefully a huge factor:

https://gis.stackexchange.com/questions/377299/adding-compression-to-a-netcdf-file-using-xarray

**Comment by rosepearson** [comment]
Thanks @CyprienBosserelle 

It looks like I will want to do something like:
```
 encode = {"data_source":  {'zlib': True, 'complevel': 1, },
                   "lidar_source":  {'zlib': True, 'complevel': 1, },
                   "z":  {'zlib': True, 'complevel': 1, }, 
                   "zo":  {'zlib': True, 'complevel': 1, }}
 dem.to_netcdf(filename, encoding=encode, format="NETCDF4", engine="netcdf4")
```

**Comment by rosepearson** [comment]
Note also need to ensure the spatial info is written into the compression as otherwise no spatial information is included. Updated example above
