### ISSUE TITLE
Use Spinx to generate docstrings

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#45]
As suggested by @jennan and previously by @kinow 

Actually do it this time :)

**Comment by kinow** [comment]
Go for it @rosepearson ! :rocket: :tada:

**Comment by rosepearson** [comment]
Trying this blog: https://www.scivision.dev/sphinx-python-quickstart/

**Comment by rosepearson** [comment]
Update - I have generated the documentation locally but am as yet a bit unsure how best to configure my folder structure / branches / Makefile to have this nicely show-up in my GH pages.

**Comment by rosepearson** [comment]
Some notes about using GitHub tokens: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by rosepearson** [comment]
merged PR
