### ISSUE TITLE
Revisit setup.py and specify a package entry point

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#46]
Comments from @jennan 

 More a question than a recommentdation: your package is declared in the "src" folder. I personally like to do the same, i.e. have a "src/package_name" organisation. Now, if you change your setup.py (I need to check how I do this) you can avoid importing from "src" (e.g. in your test code) and do it directly from geofabrics (assuming your test run in an environment where geofabrics is installed, for example via pip install -e .).
- As you are using a pyproject.toml, you can move all the information in setup.py and setup.cfg there (and keep and nearly empty setup.py to allow for pip install -e . to work). This would centralize the configuration of your package and related tools (black, flake8, etc.) as, as far as I know, they all work with the pyproject.toml file configuration.

**Comment by jennan** [comment]
Hi, the entry point refers to making `src/main.py` a CLI tool using a console_script entry point. This way, if someone install your package (e.g. via pip or conda), they can use the main script as any other CLI tool, from any folder (as it will be added to the PATH). So `python src/main.py --instructions-file ...` becomes `geofabrics --instructions-file ...` (assuming the tool is called `geofabrics` for example, but you can call the entry_point with another name of course).

See https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html for an example.

**Comment by rosepearson** [comment]
Thanks @jennan.

Something for me to do next time I need a break. Had a quick look now.

1. Seems like adding something like:

```
    entry_points={
        'console_scripts': ['geofabrics=src.main:main'],
    },
    entry_points={
        'console_scripts': ['geofabrics-benchmarking=src.benchmarking:main'],
    },
```

to the `setup.py` file will do the trick for the two scripts I have.

2. Also [https://martin-thoma.com/pyproject-toml/] seems like a reasonable example of pulling most information into a pyproject.toml.
3. And it looks like (according to this slack overflow) you ca use the following options in `setup.py` to remove the need to reference the "src" folder directly. 
```
packages=['proj'],
package_dir={'proj': 'src/proj'},
```
