### ISSUE TITLE
Support selection of LiDAR dataset(s) to use

### ISSUE THREAD

**Issue by Pooja3894** [rosepearson/GeoFabrics#49]
1. It would be great to select which dataset to use in the case of multiple datasets covering an area
2. We also will need to be able to generate the DEM from multiple LiDAR datasets :)

**Comment by rosepearson** [comment]
Hi @Pooja3894, I'll tackle the first of these in a branch for now and then close this issue until we need to create DEMs from any LiDAR datasets at which point I will reopen it :)
