### ISSUE TITLE
Support for creating DEMs from multiple LiDAR datasets

### ISSUE THREAD

**Issue by Pooja3894** [rosepearson/GeoFabrics#56]
Specifically, support the creating of a DEM over a region covered by multiple potentially overlapping LiDAR datasets.

**Comment by rosepearson** [comment]
Waikanae could be a good initial location to test this approach as the new 2021 dataset only covers the lower catchment.

**Comment by rosepearson** [comment]
Note the duplicate issue this replicates says:

> Add support for downloading multiple LiDAR datasets within a region with a set of rules defining what order the datasets are combined in.
> 
> Currently the dataset must be specified by name and only one dataset per DEM is supported. There are instances where the desired LiDAR dataset only overs some of the ROI, but other LiDAR datasets cover the remaining areas. Add support for combining LiDAR datasets in the case that the primary LiDAR dataset does not cover the full region.
> 
> Initially allow the user to specify the datasets to consider and the order to consider them. In time (future) consider adding some other filtering (i.e. date) in addition to name.

**Comment by rosepearson** [comment]
Look at applying in the hutt valley
```
"open_topography": { "NZ21_Hutt": true,
				"NZ21_UpHutt": true,
				"Wellington_2013": { "crs": { "horizontal": 2193, "vertical": 7839 } } }
```
