### ISSUE TITLE
NetCDF preparation for BGFLOOD

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#63]
This is a bit of a catch-all issue for work relating to the requirements associated with the NetCDF output from GeoFabrics (and also input to BGFLOOD).

## Requirements: 
- Store each geofabric dataset in one NetCDF file with each layer as different variables. 
  - Could also do multiple resolutions with each elevation/roughness set in a different group
  - Could also include forcing information in the same netCDF file if we want all inputs in a single file
- Include `spatial_ref` information like geotransform and crs - see section below.
  - Done using rioxarray and `write_crs()` and `write_transform`
- Include appropriate `variable` and `coordinates` attributes:
  - `units` information: See [link](https://www.unidata.ucar.edu/software/udunits/#documentation) for conventions.
  - `long_name`: A description of the variable/coordiante.
  - `standard_name`: Must be included in the NUG table.
  - `vertical_datum`: Non-standard attribute name to record the vertical datum of any elevation data.
- Record the parameters of a run:
  - Data sources should be documented in the attributes (i.e. land layer x, revision y) 
  - Capture the parameter information in a variable, or perhaps a json dump into a group attribute.
- Different resolution geofabrics should be aligned and evenly divisible (to ensure that alignment)
- ~DEMs and roughness should be defined over a full rectangular grid with no NaN values~ NaNs have since been deemed ok!

## NetCDF conventions
There are standards defining the conventions for attributes in netCDF files.
* [cfconventions.org](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch02s06.html) - The recommended standard
* [UCAR](unidata.ucar.edu/software/netcdf/conventions.html) - A repository with links to all netCDF standards
See [CF conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch02s06.html) for some details about conventions around netCDF files. 

![image](https://user-images.githubusercontent.com/22883860/163097126-e440c817-6225-4e2e-9f91-37d1e0c07368.png)

### The `spatial_ref` coordinate
This is where information associated with the coordinate system and projection (CRS and transform) are encoded.

![image](https://user-images.githubusercontent.com/22883860/163109258-6f7900c7-85a1-43cd-a7de-b2591ed2564a.png)
![image](https://user-images.githubusercontent.com/22883860/163109360-ef843e6b-9fc2-4d65-9393-2a196b961034.png)

#### Coordinate systems CF-1.6 <--> CRS
There is an optional grid mapping attribute called `crs_wkt` may be used to specify multiple coordinate system properties in so-called well-known text format (usually abbreviated to CRS WKT or OGC WKT) as detailed in the [cfconventions.org page](https://cfconventions.org/cf-conventions/cf-conventions.html#use-of-the-crs-well-known-text-format). With example mappings at the [github page](https://github.com/cf-convention/cf-conventions/wiki/Mapping-from-CF-Grid-Mapping-Attributes-to-CRS-WKT-Elements).

It looks like this information is sometimes encoded within a "spatial_ref" coordinate (see [issue](https://github.com/opendatacube/datacube-core/issues/837)).
![image](https://user-images.githubusercontent.com/22883860/163107084-867ea21e-c45d-430a-ae87-dd25aef9d1da.png)

## Python Libraries
There are various Python libraries for interacting with NetCDF files including [netCDF4](https://pypi.org/project/netCDF4/), [xarray](https://docs.xarray.dev/en/stable/index.html#), and [rioxarray](https://corteva.github.io/rioxarray/html/index.html). *netCDF4* is an engine used by *xarray* to read and write netCDF files. *xarray* has some power constructs for constructing and interacting with data stored in netCDF files. *rioxarray* combines *xarray* with *rasterio* by providing access to the *rasterio* engine with the **rio** accessor.

*xarray* supports two main objects - **DataArrays** and **DataSets**. **DataArrays** work well for a single layer of data (possibly across many bands), and the **DataSet** class should be used for multiple variables that may have different dimension (i.e. different resolutions, or x,y vs time). 

## Other
There is potential for a translation layer between GeoFabrics and BG-FLOOD or also between the catchment generation code and either GeoFabrics and/or BG-FLOOD. This would be contained in a separate repository to either.

**Comment by rosepearson** [comment]
I've been exploring how to save netCDF files out if they are datasets. At this stage I can't figure out how to encode CRS information in a Dataset vs a Dataarray such that is will be read in by rioxarray :(

I've also looked into grouped data. Waiting to hear back from @AliceHarang and @CyprienBosserelle as to if this is the expected form!

Just to note, I don't get the groups showing up in PyNcView, but I can open each group in Xarray.Info: 
* data_resolution_5.nc - 
![image](https://user-images.githubusercontent.com/22883860/162890404-17bd98a1-6c0c-4f32-9930-b425ddd322bc.png)

* data_resolution_10.nc - 
![image](https://user-images.githubusercontent.com/22883860/162890376-d6098ce1-5e32-47cf-b006-6fbf5876d5d7.png)

* grouped_data.nc - this has two groups "/resolution_5" and "/resolution_10", with the data in data_resolution_5.nc and data_resolution_10.nc respectively. i.e. I was trying to give an example of a single netCDF file with multiple resolutions.

Open questions:
* What do you the modellers think? 
* Do we want to go with grouped data, or keep them separate?
* Should I add other attributes like ymin/ymax, xmin/xmax? 
* Is the _FillValue in the form you expect?

**Comment by CyprienBosserelle** [comment]
I think we need to explore and discuss the different netcdf conventions that suits the data best. An stick to the selected conventions. This is valid for both BGFlood and geofabric.

**Comment by rosepearson** [comment]
Yes - good point @CyprienBosserelle - and as you can see from some of my previous comments I've been having trouble establishing exactly what these are. I'm going to investigate a little more how exactly the python library rioxarray encodes CRS information - something I obviously should have done before advocating for its use. I'll remove the BG-FLOOD issue I've created if this investigation suggests we shouldn't be encoding CRS info to be encoded with the netCDG file!

It'd be great to better understand what you've been doing for your netCDF files and where you're planning to go with your netCDF files so we can hopefully make geofabrics  and BG-FLOOD more similar - especially while I'm making these changes to GeoFabrics. I'm curious to understand what you are doing with adaptive grids - separate netCDF files or one netCDF file with multiple resolutions in different groups.

I'm going to set up a 30min meeting to understand what's already being done/planned in BG-FLOOD so I can adopt where it makes sense in GeoFabrics. Let me know if I should shift the proposed meeting time.

**Comment by rosepearson** [comment]
There is a bit of documentation already in BG-FLOOD
* https://github.com/CyprienBosserelle/BG_Flood/wiki/Manual#general-comment-about-input-files
* https://github.com/CyprienBosserelle/BG_Flood/wiki/Manual#wind-atm-pressure-forcing

**Comment by rosepearson** [comment]
Notes on writing out CRS information with Python libraries:
* rioxarray and Xarray don't seem to play nice when it comes to transform and crs information.
  * rioxarray.rio.set_crs(..) doesn't seem to result in the information being written in a form it will be read in by QGIS or even rioxarray, while rioxarray.rio.write_crs(..) does
