### ISSUE TITLE
Roughness length followup

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#78]
Revisit the roughness length calculations to make the estimated values more physically realistic.

Selected for this issue:
1. Revisit the equations - grass is too smooth. Also ensure appropriate limits on values - >0, and not too big <- add as instruction file input

Options:
* Set the river zo values based on the reach classification - *planning to take from the river network + flow + friction file* 
* Adjust low roughness values based on the substrate - *set for roads*
* Allow the offshore and waterway zo values to be set in the instruction file
* Include the elevation gradient to correct the std across sloped grid cells

**Comment by rosepearson** [comment]
Have had a quick look at approaches to filtering the elevations to give a maximum gradient in the immediate area. The thought is this could be used to temper the impact of the ground slope on the standard deviation of ground and ground cover points.

Built in filters include:
* `scipy.ndimage.gaussian_gradient_magnitude`
* `scipy.ndimage.generic_gradient_magnitude`

Plot of a gradient filter applied to elevation:
`fig, ax = matplotlib.pyplot.subplots(); img = ax.imshow(scipy.ndimage.gaussian_gradient_magnitude(dem.z.data, sigma=1, truncate=1)); bar = matplotlib.pyplot.colorbar(img); matplotlib.pyplot.show()`

**Comment by rosepearson** [comment]
![image](https://user-images.githubusercontent.com/22883860/172592297-622ab27a-a646-4565-941d-0f3c2a58aeee.png)

**Comment by rosepearson** [comment]
Reach classification / roughness - Graeme has created an empirical relationship between river category and mannings n. He approximated with a linear relationship. We do not yet have a similar arrangement for Zo. See https://git.niwa.co.nz/flood-resilience-aotearoa/cylc-geofabrics/-/blob/main/README.md for details on the linear approach. The broad trend is mannings N increases with category.

**Comment by rosepearson** [comment]
*Bug* - Large value in river North of Napier

*Description* 
1. Getting unexpected large values in the river N of Napier and a few other areas. 
![image](https://user-images.githubusercontent.com/22883860/223575146-7c36c0e8-6f00-47a7-b64a-1bfaac844b1e.png)
2. Nothing obvious in the point cloud
![image](https://user-images.githubusercontent.com/22883860/223575282-14d2b171-8a94-44a2-9544-ff602b5678a7.png)
![image](https://user-images.githubusercontent.com/22883860/223575389-46c681a1-d7f2-436b-b355-37380b21c318.png)

**Comment by AliceHarang** [comment]
![image](https://github.com/rosepearson/GeoFabrics/assets/82012970/db6f7186-e8ff-4f16-acb4-827b38cbaee1)

Roughness "zebra" in the Tolaga Bay region (from tiles produces for the Cyclone Gabrielle recovery project). 
The roughness get very high in these 3 zebra zones (zo in [0.5, 7]).

Zoom in:
![image](https://github.com/rosepearson/GeoFabrics/assets/82012970/5c598d27-67c0-478f-bc07-9be14826fc7e)

**Comment by AliceHarang** [comment]
On the Tolaga Bay geofabric layer, I also observed a strong rendering of powerlines on the roughness length:
![image](https://github.com/rosepearson/GeoFabrics/assets/82012970/c035781c-0a75-49ba-aa42-e78591040b82)
This is the aerial image for comparaison:
![image](https://github.com/rosepearson/GeoFabrics/assets/82012970/5de8de08-6917-469c-8879-eb014c0cf475)
This is around the town of "Tolaga Bay", near the Uawa river. (It also create false "bridges" on the river along the town.)

**Comment by rosepearson** [comment]
Revisiting this - current scope:
* Allow default values to be defined in the instruction file. (E.G. ground, waterway, road, river values to be set). 
* Bring in roads from OSM if a road value is set
* Bring in powerlines from OSM (optional) if the powerlines option is set and explore dropping the high values here
* Update the equation to divide the STD by less and to allow the value to be set in the instruction files.

And also look at the LiDAR tiles point clouds to understand the tolaga bay zebra, and also where there is strips (hunch n returns varying).
